# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Github Username'),
        ),
    ]
