# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-09 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
