# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-09 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20161209_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='uid',
        ),
    ]
