# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-09 02:48
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20161209_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uid',
            field=models.CharField(default=articles.models.unique_id, editable=False, max_length=5, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
