# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='slug'),
        ),
    ]
