# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170130_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine', models.DecimalField(decimal_places=11, max_digits=12, verbose_name='余弦相似值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_source_similarity', to='articles.Article')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_target_similarity', to='articles.Article')),
            ],
        ),
    ]
