# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20161209_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='catalog',
            field=models.CharField(choices=[('programing', '编程'), ('software', '软件'), ('thinking', '随想')], max_length=16, verbose_name='目录'),
        ),
    ]
