# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articlesimilarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='可见性'),
        ),
    ]
