# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('link', models.URLField(verbose_name='监控链接')),
                ('regex', models.CharField(max_length=255, verbose_name='正则表达式')),
                ('data', models.CharField(default='', max_length=512)),
                ('type', models.IntegerField(choices=[(1, '包含'), (2, '不包含'), (3, 'Ping'), (4, '大于'), (5, '小于'), (6, '等于')])),
                ('frequency', models.IntegerField(choices=[(1, '每5分钟'), (2, '每1小时'), (3, '每12小时')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
