# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='triggered',
            field=models.BooleanField(default=False, verbose_name='被触发'),
        ),
    ]
