# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitortask_triggered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitortask',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='monitortask',
            name='selected_element',
            field=models.CharField(default='', max_length=1024, verbose_name='匹配元素'),
        ),
    ]
