# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170213_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='selected_element',
            field=models.CharField(default='', max_length=1024, verbose_name='匹配元素'),
        ),
    ]
