# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170213_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='need_render',
            field=models.BooleanField(default=False, verbose_name='需要渲染'),
        ),
    ]
