# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitortask_need_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '推特')])),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('data', models.TextField(verbose_name='数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
