# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('url', models.URLField(verbose_name='Feed 链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('link', models.URLField(verbose_name='链接')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('indexed_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed', verbose_name='订阅')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
