# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='homepage',
            field=models.URLField(default='#', verbose_name='主页'),
        ),
    ]
