# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='homepage',
            field=models.CharField(default='#', max_length=128, verbose_name='主页'),
        ),
    ]
